Repository tesis-cabal-cugno-moreyra/webapp, pull requests merged in 2021-06, with the labels that each got.

#80 PD-018 Vista de métricas por incidente
  src/components/MapModal.vue
  src/router/index.js
  src/store/incident/actions.js
  src/views/CreateIncident.vue
  src/views/IncidentMetrics.vue
  src/views/IncidentsView.vue
Labels: enhancement, sprint-7

#87 Refactor ResourceStatistics view
  src/router/index.js
  src/store/domain-config/actions.js
  src/views/IncidentMetrics.vue
  src/views/ResourceManager.vue
  src/views/ResourceStatistics.vue
Labels: sprint8

#81 Se puede entrar con enter a la sesion
  src/components/LogoutModal.vue
  src/components/NavBar.vue
  src/views/Login.vue
Labels: sprint8

#72 Fix de los tipos de recursos
  src/components/IncidentResourceList.vue
  src/components/IncidentResourceManager.vue
  src/components/SeeUserProfiles.vue
  src/components/SignInResource.vue
  src/components/SignInSupervisor.vue
  src/views/ResourceManager.vue
Labels: bug, sprint8

#75 Fix random problems
  src/components/LogoutModal.vue
  src/components/NavBar.vue
Labels: bug, sprint8
